// Generated by https://quicktype.io
export interface FetchAllProductResponse {
  count: number;
  next: null;
  previous: null;
  results: SmallProduct[];
}

export interface SmallProduct {
  name: string;
  url: string;
}

export class Product {
  id: number;
  pro: string
}
