export * from './services-section/services-section.component';
export * from './ranking-section/ranking-section.component';
export * from './benefits-section/benefits-section.component';
export * from './how-it-works-section/how-it-works-section.component';
export * from './hero-section/hero-section.component';
export * from './features-section/features-section.component';
export * from './pre-footer-section/pre-footer-section.component';
export * from './user-feedbak-section/user-feedbak-section.component';
export * from './users-reviews-section/users-reviews-section.component';